services:
    brandscraper:
        container_name: brandscraper
        build: .
        deploy:
            resources:
                limits:
                    memory: 6G
                    cpus: "6"
        volumes:
            - .:/var/www
            - /var/www/node_modules
        ports:
            - "8000:8000"
            - "11434:11434"
            - "5173:5173"
            - "80:80"
        environment:
            - NODE_ENV=development
            - HOST=0.0.0.0
        command: |
            sh -c "
              # Create .env if it doesn't exist
              if [ ! -f /var/www/.env ]; then
                cp /var/www/.env.example /var/www/.env
                php artisan key:generate
              fi
              # Start services
              ollama serve --debug &
              php artisan serve --host=0.0.0.0 --port=8000 &
              npm run dev -- --host 0.0.0.0"
        restart: always
