services:
    brandscraper:
        container_name: brandscraper
        build: .
        volumes:
            - .:/var/www
            # Exclude node_modules from volume mounting to prevent overwriting
            - /var/www/node_modules
        ports:
            - "8000:8000"
            - "11434:11434"
            - "5173:5173"
            - "80:80"
        environment:
            - NODE_ENV=development
            - HOST=0.0.0.0 # Allow Vite to accept connections from outside
        command: |
            sh -c "
              ollama serve &
              php artisan serve --host=0.0.0.0 --port=8000 &
              npm run dev -- --host 0.0.0.0"
        restart: always
